# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FilePathField(),
        ),
    ]
