# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20170219_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='C:\\Users\\mar_s\\PycharmProjects\\djangotestwebsite\\storefront\\var/www/media/'),
        ),
    ]
