# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20170219_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviewlink',
            field=models.TextField(),
        ),
    ]
